-- Migration: Add performance indexes for age/event filtering
-- Date: 2026-01-27
-- Description: Fix slow data loading by adding missing indexes identified by performance analysis
-- Generated by: Performance diagnostics script

-- 1. Events indexes for filtering
-- Composite index for category + status + date range filtering (CRITICAL for age/event queries)
CREATE INDEX IF NOT EXISTS "idx_events_category_status_saleStart_saleEnd" ON "events"("category", "status", "saleStart", "saleEnd");

-- Index for city + status filtering
CREATE INDEX IF NOT EXISTS "idx_events_city_status" ON "events"("city", "status");

-- Index for date + status filtering
CREATE INDEX IF NOT EXISTS "idx_events_startDateTime_status" ON "events"("startDateTime", "status");

-- Index for organizer dashboard queries
CREATE INDEX IF NOT EXISTS "idx_events_organizerId_status" ON "events"("organizerId", "status");

-- 2. Orders index for analytics queries
-- Composite index for event analytics (eventId + status + createdAt)
CREATE INDEX IF NOT EXISTS "idx_orders_eventId_status_createdAt" ON "orders"("eventId", "status", "createdAt");

-- Index for user order history
CREATE INDEX IF NOT EXISTS "idx_orders_userId_status" ON "orders"("userId", "status");

-- 3. Tickets index for event queries
CREATE INDEX IF NOT EXISTS "idx_tickets_eventId_status" ON "tickets"("eventId", "status");

-- Index for order ticket lookups
CREATE INDEX IF NOT EXISTS "idx_tickets_orderId_status" ON "tickets"("orderId", "status");

-- 4. Ticket types index for price sorting
CREATE INDEX IF NOT EXISTS "idx_ticket_types_eventId_price" ON "ticket_types"("eventId", "price");

-- 5. Seats index for availability queries
CREATE INDEX IF NOT EXISTS "idx_seats_eventId_status_section" ON "seats"("eventId", "status", "section");
